In [1]:
import numpy as np

In [2]:
def initialize_population( num_individuals, num_variables ):
    pop = np.random.randint(2, size=(num_individuals, num_variables))
    
    return pop

In [3]:
def onemax( ind ):
    value = np.sum(ind) # cộng tất cả các giá trị của cá thể => độ thích nghi của cá thể
    
    return value

In [4]:
def evaluate_population( pop ):
    values = np.array([onemax(ind) for ind in pop])
        
    return values

In [5]:
def better_fitness( fitness_1, fitness_2, maximization=True ):
    if maximization:
        if fitness_1 > fitness_2:
            return True
    else:
        if fitness_1 < fitness_2:
            return True
        
    return False

In [6]:
def tournament_selection( pop, pop_fitness, selection_size, tournament_size):  
    num_individuals = len(pop)
    indices = np.arange(num_individuals)
    selected_indices = []
    
    while len(selected_indices) < selection_size:
        np.random.shuffle(indices)
        
        for i in range(0, num_individuals, tournament_size):
            best_idx = i
            for idx in range(1, tournament_size):
                if better_fitness(pop_fitness[indices[i+idx]], pop_fitness[indices[best_idx]]):
                    best_idx = i+idx
            selected_indices.append(indices[best_idx])

    selected_indices = np.array(selected_indices)
        
    return selected_indices

In [7]:
def variation( pop ):
    num_individuals = len(pop)
    num_parameters = len(pop[0])
    indices = np.arange(num_individuals)
    np.random.shuffle(indices)
    offspring = []
    
    for i in range(0, num_individuals, 2):
        idx1 = indices[i]
        idx2 = indices[i+1]
        offspring1 = list(pop[idx1])
        offspring2 = list(pop[idx2])
        for idx in range(0, num_parameters):
            r = np.random.rand()
            if r < 0.5:
                temp = offspring2[idx]
                offspring2[idx] = offspring1[idx]
                offspring1[idx] = temp

        offspring.append(offspring1)
        offspring.append(offspring2)
    
    offspring = np.array(offspring)
    return offspring

In [8]:
def popop(num_individuals, num_parameters, num_generations):
    pop = initialize_population(num_individuals, num_parameters)
    pop_fitness = evaluate_population(pop)
    print("#Gen 0:")
    print(pop_fitness)
    
    selection_size = len(pop)
    tournament_size = 4

    for i in range(num_generations):
        offspring = variation(pop)
        offspring_fitness = evaluate_population(offspring)
        
        pool = np.vstack((pop,offspring))
        pool_fitness = np.hstack((pop_fitness, offspring_fitness))

        pool_indices = tournament_selection(pool, pool_fitness, selection_size, tournament_size)

        pop = pool[pool_indices, :]
        pop_fitness = pool_fitness[pool_indices]
        print("#Gen {}:".format(i+1))
        print(pop_fitness)

    print("#Result:")
    print(pop)
    print(pop_fitness)

In [19]:
#TH1: num_variations = 8
np.random.seed(17520618)
num_parameters = 8
num_individuals = 8
num_generations = 10
popop(num_individuals, num_parameters, num_generations)

#Gen 0:
[3 7 4 4 5 2 0 2]
#Gen 1:
[6 7 5 4 7 6 3 6]
#Gen 2:
[7 6 6 7 6 7 5 7]
#Gen 3:
[7 7 7 7 7 7 7 7]
#Gen 4:
[7 7 8 7 8 7 7 7]
#Gen 5:
[8 8 8 8 8 8 8 8]
#Gen 6:
[8 8 8 8 8 8 8 8]
#Gen 7:
[8 8 8 8 8 8 8 8]
#Gen 8:
[8 8 8 8 8 8 8 8]
#Gen 9:
[8 8 8 8 8 8 8 8]
#Gen 10:
[8 8 8 8 8 8 8 8]
#Result:
[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]
[8 8 8 8 8 8 8 8]


In [45]:
#TH2: num_variations = 16
np.random.seed(17520619)
num_parameters = 16
num_individuals = 32
num_generations = 20
popop(num_individuals, num_parameters, num_generations)

#Gen 0:
[ 6  7  6  1  8  6 10  5  6  7 12 11  8  9  5  5  7  4  8  6  8  8  6  8
  7  8 10  9  7  5  6  7]
#Gen 1:
[ 9  9  9  8 11  9  9  8  8 12 10 10  8 10  8 12  9 12  9  8  9 10 12  9
  8  7 11  9 10  9  7  9]
#Gen 2:
[ 9 10 12 10 11 11 10 11 12 10 10 12 12  9 10 12  9 12 12 12 10 11 10 10
 12 11 12 12 10 11 12 11]
#Gen 3:
[11 13 12 12 12 12 12 12 12 13 12 12 12 12 12 11 11 12 12 13 12 11 12 13
 12 12 12 12 12 12 12 12]
#Gen 4:
[13 13 12 13 13 12 12 12 14 13 14 14 12 13 12 14 14 13 13 14 12 12 12 13
 12 14 13 14 12 13 13 13]
#Gen 5:
[14 14 14 13 14 14 14 15 13 14 14 14 14 13 15 14 15 13 14 14 14 14 14 14
 13 13 14 13 14 14 14 15]
#Gen 6:
[15 14 15 16 14 14 15 16 15 14 15 15 15 14 15 14 14 14 15 15 15 16 14 16
 15 15 14 14 15 15 14 15]
#Gen 7:
[16 16 15 14 16 15 15 16 16 15 15 16 15 15 15 15 15 16 16 15 16 15 15 15
 16 15 15 16 15 16 15 15]
#Gen 8:
[16 16 16 16 16 16 16 16 16 16 15 16 16 16 16 16 16 15 15 16 16 15 16 16
 16 16 16 16 16 16 16 16]
#Gen 9:
[16 16 16 16 16 16 16 16 16 1

In [47]:
#TH3: 
np.random.seed(17520620)
num_parameters = 32
num_individuals = 32
num_generations = 20
popop(num_individuals, num_parameters, num_generations)

#Gen 0:
[18 17 17 17 19 18 17 15 17 19 16 13 15 17 22 10 14 15 17 21 12 16 10 16
 15 23 16 14 18 12 14 17]
#Gen 1:
[18 22 19 17 15 21 18 19 20 17 21 18 23 21 19 20 21 19 17 22 23 16 21 18
 18 21 19 21 20 20 18 22]
#Gen 2:
[23 20 23 21 22 22 21 21 21 23 22 27 22 21 21 20 27 21 21 21 21 20 20 22
 23 23 22 23 19 22 22 20]
#Gen 3:
[22 23 22 23 25 25 27 24 22 21 22 23 22 24 25 24 22 23 25 23 22 24 23 25
 24 23 27 27 23 23 25 24]
#Gen 4:
[27 26 26 26 25 25 25 23 25 27 27 25 27 24 25 26 25 25 24 25 27 27 27 24
 26 25 27 26 25 25 26 26]
#Gen 5:
[27 27 26 26 27 27 27 27 28 27 29 27 27 27 27 26 25 27 28 27 27 26 27 27
 27 28 26 26 27 27 27 29]
#Gen 6:
[28 27 29 29 27 27 28 28 28 27 28 27 29 27 29 29 27 29 27 27 28 29 28 27
 28 28 27 29 27 29 28 27]
#Gen 7:
[29 29 29 30 29 29 28 29 30 30 29 29 29 29 29 27 28 30 28 29 29 29 29 30
 28 29 29 29 28 30 28 29]
#Gen 8:
[29 30 29 30 30 30 30 30 28 29 29 30 29 30 30 30 30 29 29 29 29 30 30 29
 30 30 30 30 30 30 30 30]
#Gen 9:
[30 31 30 30 30 30 30 31 30 3

In [56]:
#TH4:
np.random.seed(17520621)
num_parameters = 64
num_individuals = 64
num_generations = 20
popop(num_individuals, num_parameters, num_generations)

#Gen 0:
[30 26 27 29 36 38 30 37 35 31 24 31 38 29 27 29 28 34 33 34 34 26 34 27
 32 35 35 30 31 33 32 25 30 26 36 33 33 33 33 37 31 36 31 33 35 33 32 30
 33 28 38 30 28 36 29 31 22 38 30 33 35 28 34 39]
#Gen 1:
[39 38 35 33 36 34 37 38 37 36 35 35 35 39 36 37 35 33 33 33 38 39 35 41
 35 34 37 37 33 37 32 32 36 35 38 35 36 36 39 38 37 41 39 38 35 34 33 37
 35 36 39 36 34 33 33 35 38 33 36 36 37 34 37 36]
#Gen 2:
[38 40 41 36 38 40 37 36 39 39 37 41 36 40 39 39 41 39 41 41 39 38 37 39
 41 39 38 38 38 40 39 40 40 39 38 40 38 41 40 39 35 38 38 39 39 35 37 38
 41 41 41 41 37 37 40 37 37 39 39 41 36 40 39 37]
#Gen 3:
[41 41 41 44 39 40 41 41 41 44 41 40 41 38 42 40 41 42 44 42 40 39 41 41
 39 40 40 46 40 44 40 41 41 42 39 40 40 41 44 41 41 41 40 46 42 44 40 41
 44 41 40 41 44 41 41 40 41 40 40 41 42 41 41 39]
#Gen 4:
[41 43 41 42 41 46 44 41 46 42 43 44 42 44 46 46 49 44 43 44 46 46 41 41
 44 42 42 46 44 44 42 44 46 46 46 43 43 44 41 41 49 44 44 46 46 45 40 42
 41 44 44 41 41 44 42 45 42 41

In [60]:
#TH5:
np.random.seed(17520622)
num_parameters = 128
num_individuals = 64
num_generations = 40
popop(num_individuals, num_parameters, num_generations)

#Gen 0:
[70 62 75 62 67 56 66 61 59 64 64 62 61 52 67 58 55 66 69 58 60 59 64 68
 56 63 58 63 58 68 55 64 60 62 66 70 65 63 57 59 63 62 66 68 64 65 66 58
 62 68 65 63 59 59 62 64 65 61 60 64 57 60 63 71]
#Gen 1:
[69 69 63 66 72 66 64 67 68 67 67 66 64 66 70 67 75 67 66 67 63 68 66 67
 67 66 72 69 64 71 65 68 70 59 68 72 66 67 69 69 72 64 65 66 63 66 66 70
 67 68 67 70 64 67 65 75 73 66 63 66 65 65 67 71]
#Gen 2:
[66 75 72 67 71 70 74 75 70 69 68 72 70 70 71 76 66 72 73 74 70 72 66 72
 72 67 73 69 75 68 72 73 74 71 72 70 73 68 75 67 72 73 76 73 69 68 72 75
 75 75 72 69 67 71 67 70 67 71 72 70 72 75 74 69]
#Gen 3:
[75 79 75 74 73 76 81 74 75 72 74 73 70 76 69 72 73 69 75 70 72 77 76 76
 75 76 76 73 73 74 78 73 79 74 77 76 72 75 81 75 75 72 73 74 74 75 74 76
 74 73 75 73 72 76 76 75 72 74 72 78 74 74 76 73]
#Gen 4:
[83 81 79 76 76 79 78 75 81 78 77 77 78 83 83 79 76 80 80 72 82 84 79 77
 83 76 76 78 81 73 77 75 81 80 74 76 79 78 79 77 78 82 80 83 83 74 81 76
 84 75 74 76 78 75 79 76 78 81